--
-- Plik wygenerowany przez SQLiteStudio v3.2.1 dnia czw. sie 15 18:28:45 2019
--
-- U¿yte kodowanie tekstu: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Tabela: Anteny
CREATE TABLE Anteny (Id_ant INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, Czestotliwosc TEXT NOT NULL, Opis TEXT);

-- Tabela: Dane
CREATE TABLE Dane (Id_prof INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, Typ_prof INTEGER REFERENCES Typ_prof (Id_typ) ON DELETE RESTRICT NOT NULL, Nazwa TEXT NOT NULL, Profil TEXT NOT NULL, Data DATE NOT NULL, Id_miejsc INTEGER NOT NULL REFERENCES Miejscowosc (Id_miejsc) ON DELETE RESTRICT, Wspol_pocz REAL, Wspol_konca REAL, Wspol_opisowe_pocz TEXT NOT NULL, Wspol_opisowe_konca TEXT NOT NULL, Dl_prof REAL NOT NULL, Liczba_tras INTEGER NOT NULL, Odl_m_trasami REAL NOT NULL, Markery TEXT, Id_ant INTEGER REFERENCES Anteny (Id_ant) ON DELETE RESTRICT NOT NULL, Id_osoby INTEGER REFERENCES Osoby (Id_osoby) ON DELETE RESTRICT NOT NULL, Id_pogody INTEGER NOT NULL REFERENCES Pogoda (Id_pog) ON DELETE RESTRICT, Id_podl INTEGER NOT NULL REFERENCES Podloze (Id_podl) ON DELETE RESTRICT, Uwagi TEXT);

-- Tabela: Foto
CREATE TABLE Foto (Id_fot INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, Zdjecie BLOB NOT NULL, Nazwa TEXT NOT NULL, Opis TEXT NOT NULL, Id_prof INTEGER NOT NULL, Czy_mapa BOOLEAN NOT NULL DEFAULT (0));

-- Tabela: Markery
CREATE TABLE Markery (Id_mark INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, Id_prof INTEGER NOT NULL REFERENCES Dane ON DELETE CASCADE, Nr_mark INTEGER NOT NULL DEFAULT (1), Nazwa TEXT NOT NULL, Opis TEXT);

-- Tabela: Miejscowosc
CREATE TABLE Miejscowosc (Id_miejsc INTEGER NOT NULL, Miejscowosc TEXT NOT NULL UNIQUE, Id_panstwo INTEGER NOT NULL REFERENCES Panstwo (Id_panstwo) ON DELETE RESTRICT, CONSTRAINT PK_Miejscowosc PRIMARY KEY (Id_miejsc));

-- Tabela: Osoby
CREATE TABLE Osoby (Id_osoby INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, Imie TEXT NOT NULL, Nazwisko TEXT NOT NULL, Stanowisko TEXT);

-- Tabela: Panstwo
CREATE TABLE Panstwo (Id_panstwo INTEGER NOT NULL, Panstwo TEXT NOT NULL UNIQUE, CONSTRAINT PK_Panstwo PRIMARY KEY (Id_panstwo));

-- Tabela: Podloze
CREATE TABLE Podloze (Id_podl INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, Opis TEXT NOT NULL UNIQUE);

-- Tabela: Pogoda
CREATE TABLE Pogoda (Id_pog INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, Objaw TEXT NOT NULL UNIQUE);

-- Tabela: Projekt
CREATE TABLE Projekt (Id_proj INTEGER NOT NULL, Nazwa_proj TEXT NOT NULL UNIQUE, Id_miejscowosc INTEGER NOT NULL REFERENCES Miejscowosc (Id_miejsc) ON DELETE RESTRICT, Opis TEXT, Klient TEXT, CONSTRAINT PK_Projekt PRIMARY KEY (Id_proj));

-- Tabela: Typ_prof
CREATE TABLE Typ_prof (Id_typ INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL, Typ TEXT NOT NULL UNIQUE);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
